In [130]:
import json
import pandas as pd

In [131]:
with open('../data/raw/example_1.json', 'r') as file:
    data = json.load(file)

In [132]:
df = pd.DataFrame(data)

In [133]:
df.head()

,https://www.domain.com.au/1208-50-albert-street-south-melbourne-vic-3205-17193635,https://www.domain.com.au/64-mills-street-albert-park-vic-3206-16254842,https://www.domain.com.au/11-barnato-st-weir-views-vic-3338-16482891,https://www.domain.com.au/1104-70-southbank-boulevard-southbank-vic-3006-15846616,https://www.domain.com.au/167-charman-road-beaumaris-vic-3193-17193619,https://www.domain.com.au/10-135-ormond-esplanade-elwood-vic-3184-17193581,https://www.domain.com.au/2-107-addison-street-elwood-vic-3184-17193576,https://www.domain.com.au/3-18-joyce-street-elwood-vic-3184-17193573,https://www.domain.com.au/2-435-st-kilda-st-elwood-vic-3184-17171549,https://www.domain.com.au/305-101-bay-street-port-melbourne-vic-3207-17193493,...,https://www.domain.com.au/96-macclesfield-rd-monbulk-vic-3793-16994018,https://www.domain.com.au/44-kalbian-drive-clyde-north-vic-3978-16430829,https://www.domain.com.au/1-wordsworth-street-st-kilda-vic-3182-16956336,https://www.domain.com.au/13-adelaide-st-blairgowrie-vic-3942-15791609,https://www.domain.com.au/160-moore-rd-sunbury-vic-3429-16902107,https://www.domain.com.au/176-scotchmans-rd-drysdale-vic-3222-16884014,https://www.domain.com.au/485-punt-road-south-yarra-vic-3141-16773920,https://www.domain.com.au/4-vital-drive-tarneit-vic-3029-16625114,https://www.domain.com.au/14-sheffield-way-keysborough-vic-3173-15470011,https://www.domain.com.au/4-ocean-park-drive-marengo-vic-3233-13210948
name,"1208/50 Albert Street, South Melbourne VIC 3205","64 Mills Street, Albert Park VIC 3206","11 Barnato St, Weir Views VIC 3338","1104/70 Southbank Boulevard, Southbank VIC 3006","167 Charman Road, Beaumaris VIC 3193","10/135 Ormond Esplanade, Elwood VIC 3184","2/107 Addison Street, Elwood VIC 3184","3/18 Joyce Street, Elwood VIC 3184","2/435 St Kilda St, Elwood VIC 3184","305/101 Bay Street, Port Melbourne VIC 3207",...,"96 Macclesfield Rd, Monbulk VIC 3793","44 Kalbian Drive, Clyde North VIC 3978","1 Wordsworth Street, St Kilda VIC 3182","13 Adelaide St, Blairgowrie VIC 3942","160 Moore rd, Sunbury VIC 3429","176 Scotchmans Rd, Drysdale VIC 3222","485 Punt Road, South Yarra VIC 3141","4 Vital drive, Tarneit VIC 3029","14 Sheffield Way, Keysborough VIC 3173","4 Ocean Park Drive, Marengo VIC 3233"
cost_text,$520 pw,$1495.00,$460 per week ($1999 pcm),$420,$950.00,"$1,200 weekly",$895 weekly,$870 weekly,$675 weekly,$595 weekly,...,$750 pw,$850 Per Week,"$2,500",$850 weekly,$1100 Per Week,"$1,800 weekly","$1,450.00",$550,$625 / wk,from $300 per night
rooms,"[1 Bed, 1 Bath]","[3 Beds, 1 Bath]","[4 Beds, 2 Baths]","[1 Bed, 1 Bath]","[4 Beds, 3 Baths]","[3 Beds, 2 Baths]","[3 Beds, 2 Baths]","[2 Beds, 2 Baths]","[2 Beds, 1 Bath]","[1 Bed, 1 Bath]",...,"[5 Beds, 2 Baths]","[5 Beds, 3 Baths]","[5 Beds, 3 Baths]","[5 Beds, 3 Baths]","[5 Beds, 2 Baths]","[7 Beds, 4 Baths]","[6 Beds, 2 Baths]","[5 Beds, 2 Baths]","[5 Beds, 2 Baths]","[5 Beds, 2 Baths]"
parking,[1 Parking],[− Parking],[2 Parking],[− Parking],[2 Parking],[2 Parking],[1 Parking],[1 Parking],[1 Parking],[1 Parking],...,[− Parking],[2 Parking],[1 Parking],[2 Parking],[− Parking],[6 Parking],[3 Parking],[2 Parking],[2 Parking],[2 Parking]
desc,Carson Mair,Sally McCormack,Kavinda Kudage Don,Kim Te,Simone Buckley,Jemma Wilksch,Tina Kelly,Tina Kelly,Jemma Wilksch,Jemma Wilksch,...,Welcome to 96 Macclesfield Rd Monbulk!\nThis s...,Royal Melbourne Estates presents to you 44 Kal...,"Nestled within a coveted beachside setting, th...","Available for long term tenancy, and perfectly...","Bring your horses,kids plus your in- laws .\nT...","This is a majestic property, and certainly amo...",** Click the BOOK INSPECTION button to registe...,Bal Real Estate proudly presents this brillian...,** LEASED BY AQUIRE**\nThis immaculately prese...,"Double story, 5 bedroom home, with open plan l..."

In [134]:
# swap rows and columns
df= df.transpose()

In [135]:
df

,name,cost_text,rooms,parking,desc
https://www.domain.com.au/1208-50-albert-street-south-melbourne-vic-3205-17193635,"1208/50 Albert Street, South Melbourne VIC 3205",$520 pw,"[1 Bed, 1 Bath]",[1 Parking],Carson Mair
https://www.domain.com.au/64-mills-street-albert-park-vic-3206-16254842,"64 Mills Street, Albert Park VIC 3206",$1495.00,"[3 Beds, 1 Bath]",[− Parking],Sally McCormack
https://www.domain.com.au/11-barnato-st-weir-views-vic-3338-16482891,"11 Barnato St, Weir Views VIC 3338",$460 per week ($1999 pcm),"[4 Beds, 2 Baths]",[2 Parking],Kavinda Kudage Don
https://www.domain.com.au/1104-70-southbank-boulevard-southbank-vic-3006-15846616,"1104/70 Southbank Boulevard, Southbank VIC 3006",$420,"[1 Bed, 1 Bath]",[− Parking],Kim Te
https://www.domain.com.au/167-charman-road-beaumaris-vic-3193-17193619,"167 Charman Road, Beaumaris VIC 3193",$950.00,"[4 Beds, 3 Baths]",[2 Parking],Simone Buckley
...,...,...,...,...,...
https://www.domain.com.au/176-scotchmans-rd-drysdale-vic-3222-16884014,"176 Scotchmans Rd, Drysdale VIC 3222","$1,800 weekly","[7 Beds, 4 Baths]",[6 Parking],"This is a majestic property, and certainly amo..."
https://www.domain.com.au/485-punt-road-south-yarra-vic-3141-16773920,"485 Punt Road, South Yarra VIC 3141","$1,450.00","[6 Beds, 2 Baths]",[3 Parking],** Click the BOOK INSPECTION button to registe...
https://www.domain.com.au/4-vital-drive-tarneit-vic-3029-16625114,"4 Vital drive, Tarneit VIC 3029",$550,"[5 Beds, 2 Baths]",[2 Parking],Bal Real Estate proudly presents this brillian...
https://www.domain.com.au/14-sheffield-way-keysborough-vic-3173-15470011,"14 Sheffield Way, Keysborough VIC 3173",$625 / wk,"[5 Beds, 2 Baths]",[2 Parking],** LEASED BY AQUIRE**\nThis immaculately prese...
https://www.domain.com.au/4-ocean-park-drive-marengo-vic-3233-13210948,"4 Ocean Park Drive, Marengo VIC 3233",from $300 per night,"[5 Beds, 2 Baths]",[2 Parking],"Double story, 5 bedroom home, with open plan l..."

In [136]:
df.count()

name         2664
cost_text    2664
rooms        2664
parking      2664
desc         2664
dtype: int64

In [137]:
# calculate bedrooms number
df['Bed'] = df['rooms'].astype(str).str.extract(r'(\d+)\s*Beds?')

In [138]:
import re

# convert rent to weekly rent
def convert_to_weekly(cost_text):
    # convert text to lower case
    cost_text = cost_text.lower().replace(',', '')
    
    # get all prices in texts
    amounts = re.findall(r'(\d+\.?\d*)', cost_text)
    amounts = [float(amount) for amount in amounts]
    
    if not amounts:
        return None 
    
    # weekly rent is prioritised
    if 'pw' in cost_text or 'per week' in cost_text or 'weekly' in cost_text or '/ wk' in cost_text or 'p/w' in cost_text:
        return amounts[0]  
    # victoria rent calculating method
    elif 'pcm' in cost_text or 'per month' in cost_text:
        return (amounts[-1] * 12) / 365 * 7 
    elif 'per night' in cost_text :
        return amounts[0] * 7  
    else:
        return amounts[0]  

# apply to cost text
df['weekly_rent'] = df['cost_text'].apply(convert_to_weekly)

In [139]:
df.count()

name           2664
cost_text      2664
rooms          2664
parking        2664
desc           2664
Bed            2664
weekly_rent    2627
dtype: int64

In [140]:
# Remove rows where 'weekly_rent' is NaN
df = df.dropna(subset=['weekly_rent'])

# Display the cleaned DataFrame
print(df.count())

name           2627
cost_text      2627
rooms          2627
parking        2627
desc           2627
Bed            2627
weekly_rent    2627
dtype: int64

In [141]:
# drop url index and unnessary columns
df = df.reset_index(drop=True)
df = df.drop(['cost_text','rooms','desc', 'parking'], axis=1)

In [142]:
df

                                                 name Bed  weekly_rent
0     1208/50 Albert Street, South Melbourne VIC 3205   1        520.0
1               64 Mills Street, Albert Park VIC 3206   3       1495.0
2                  11 Barnato St, Weir Views VIC 3338   4        460.0
3     1104/70 Southbank Boulevard, Southbank VIC 3006   1        420.0
4                167 Charman Road, Beaumaris VIC 3193   4        950.0
...                                               ...  ..          ...
2622             176 Scotchmans Rd, Drysdale VIC 3222   7       1800.0
2623              485 Punt Road, South Yarra VIC 3141   6       1450.0
2624                  4 Vital drive, Tarneit VIC 3029   5        550.0
2625           14 Sheffield Way, Keysborough VIC 3173   5        625.0
2626             4 Ocean Park Drive, Marengo VIC 3233   5       2100.0

[2627 rows x 3 columns]

In [143]:
# Create a condition to check if the name has a flat number (pattern "number/")

df['Apartment'] = df['name'].apply(lambda x: 1 if '/' in x else 0)
df.head(5)

                                              name Bed  weekly_rent  Apartment
0  1208/50 Albert Street, South Melbourne VIC 3205   1        520.0          1
1            64 Mills Street, Albert Park VIC 3206   3       1495.0          0
2               11 Barnato St, Weir Views VIC 3338   4        460.0          0
3  1104/70 Southbank Boulevard, Southbank VIC 3006   1        420.0          1
4             167 Charman Road, Beaumaris VIC 3193   4        950.0          0

In [144]:
# Function to extract the suburb and postcode from the 'name' column
def extract_location_postcode(address):
    # Regex pattern to capture the suburb name and postcode (VIC followed by 4 digits)
    pattern = r'(?P<suburb>[A-Za-z\s]+) VIC (?P<postcode>\d{4})'
    match = re.search(pattern, address)
    if match:
        return match.group('suburb').strip(), match.group('postcode')
    return None, None

# Apply the function to each row in the 'name' column
df['Location'], df['Postcode'] = zip(*df['name'].apply(extract_location_postcode))

# delete name column
df = df.drop(columns=['name'])

# Display the modified dataframe
df.head()

  Bed  weekly_rent  Apartment         Location Postcode
0   1        520.0          1  South Melbourne     3205
1   3       1495.0          0      Albert Park     3206
2   4        460.0          0       Weir Views     3338
3   1        420.0          1        Southbank     3006
4   4        950.0          0        Beaumaris     3193

In [145]:
df = df.groupby(['Location', 'Bed', 'Apartment']).agg(
    Count=('weekly_rent', 'size'),    # Count number of rows
    Median=('weekly_rent', 'median')  # Median of weekly_rent
).reset_index()

In [146]:
# Manually add 'Year' and 'Month' columns with a fixed value (2023 and August)

df['Year'] = 2024
df['Month'] = 'Aug'

In [147]:
# Define the path for the "curated data" folder
file_path = '../data/landing/2024_rent.csv'

# Save the DataFrame to the specified path in CSV format
df.to_csv(file_path, index=False)